# Settings for the app
app:
  # HTML Title
  title: CDOT | Request Bike Parking
  # Header name
  name: Request Bike Parking
  # Meta description that will show up in Google search results
  meta_description: _()
  # Meta author that will show up in Google search results
  meta_author: Chicago Department of Transportation


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 41.8819
      lng: -87.6278
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: http://{s}.tiles.mapbox.com/v3/openplans.CDOT_BikeRacks/{z}/{x}/{y}.png

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bikeparking:
    label: _(Bike Parking)
    rules:
      - condition: '"{{location_type}}" === "bikeparking" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/marker-bike-lock.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [62, 81]
          shadowSize: [95, 81]
          iconAnchor: [31, 81]

      - condition: '"{{location_type}}" === "bikeparking"'
        icon:
          iconUrl: /static/css/images/marker-dot.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]

  bikeparkingrejected:
    label: _(Bike Parking)
    rules:
      - condition: '"{{location_type}}" === "bikeparkingrejected" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/marker-bike-lock-rejected.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [62, 81]
          shadowSize: [95, 81]
          iconAnchor: [31, 81]

      - condition: '"{{location_type}}" === "bikeparkingrejected"'
        icon:
          iconUrl: /static/css/images/marker-dot-rejected.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]

  bikeparkingapproved:
    label: _(Bike Parking)
    rules:
      - condition: '"{{location_type}}" === "bikeparkingapproved" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/marker-bike-lock-approved.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [62, 81]
          shadowSize: [95, 81]
          iconAnchor: [31, 81]

      - condition: '"{{location_type}}" === "bikeparkingapproved"'
        icon:
          iconUrl: /static/css/images/marker-dot-approved.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Request Bike Parking)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Requests)
  show_map_button_label: _(Show the Map)
  title: _(My Request)
  action_text: _(requested)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit Request)
  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
        - key: required
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    # - prompt: _(Location Type)
    #   type: select
    #   options:
    #     - label: _(Choose One)
    #       value: ''
    #     - label: _(Requested)
    #       value: bikeparking
    #     - label: _(Rejected)
    #       value: bikeparkingrejected
    #     - label: _(Approved)
    #       value: bikeparkingapproved
    #   name: location_type
    #   attrs:
    #     - key: required
    - type: hidden
      name: location_type
      attrs:
      - key: value
        value: bikeparking

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    # start_page: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email